# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Autosubmission

on:
  # when committing to master
  push:
    # FIXME: master only
    branches: [ master, autosubmission ]

  # allow running manually
  workflow_dispatch:

jobs:
  submit:
    # do not run in forks
    # FIXME: if: github.repository_owner == 'yast'

    runs-on: ubuntu-latest

    # the default timeout is 6 hours, do not wait for that long if osc gets stucked
    timeout-minutes: 60

    steps:
      - name: Autosubmission
        uses: lslezak/actions@main
        with:
          obs_user:     ${{ secrets.OBS_USER }}
          obs_password: ${{ secrets.OBS_PASSWORD }}
